export const START_ACTIVITY = "START_ACTIVITY";
export const PAUSE_ACTIVITY = "PAUSE_ACTIVITY";
export const RESUME_ACTIVITY = "RESUME_ACTIVITY";
export const FINISH_ACTIVITY = "FINISH_ACTIVITY";
export const ADD_COORDINATE = "ADD_COORDINATE";
